#pragma once

enum class GunState {IDLE, SHOOT, RELOAD};
enum class GameState{IDLE,RECEIVE, SETTINGS, PREGAME, GAME, SEND, FINISH, WINNERSCREEN};
enum class DisplayState {SETTINGS, PREGAME, GAME, FINISH};
enum class MenuState {IDLE, MENU, BULLETS, LIVES, PLAYER_COUNT, PLAY_TIME};
enum class DisplayMenuState {IDLE, MENU, RECEIVE, BULLETS, LIVES, PLAYER_COUNT, PLAY_TIME, DONE, ERROR, GAME, FINISH_PLAYER, FINISH_HOST};
enum class BeeperState{ IDLE, SHOOT, RELOAD, EMPTY_CLIP, HIT };
